App\Entity\Foo:
  attributes:
    id:
      groups: ['foo:read', 'foo:read:collection', 'foo:export:collection']
    code:
      groups: ['foo:read', 'foo:read:collection', 'foo:write', 'foo:export:collection']
    label:
      groups: ['foo:read', 'foo:read:collection', 'foo:write', 'foo:export:collection']
    exportedAt:
      groups: ['foo:export:collection']
    base64:
      groups: ['foo:read:collection', 'foo:export:collection']

