resources:
  App\Entity\Foo:
    formats:
      json: ['application/json']
      jsonld: ['application/ld+json']
    normalizationContext:
      groups: ['foo:read']
    denormalizationContext:
      groups: ['foo:write']
    operations:
        ApiPlatform\Metadata\GetCollection:
          normalizationContext:
            groups: ['foo:read:collection']
          filters: ['foo.search_filter']
        ApiPlatform\Metadata\Post:
          denormalizationContext:
            groups: ['foo:write']
        ApiPlatform\Metadata\Get:
          normalizationContext:
            groups: ['foo:read']
        ApiPlatform\Metadata\Delete: ~
        ApiPlatform\Metadata\Put: ~
        foo_export:
          class: ApiPlatform\Metadata\GetCollection
          method: GET
          uriTemplate: /export_foos
          controller: ApiPlatform\Action\PlaceholderAction
          formats:
            csv: ['text/csv']
          normalizationContext:
            groups: ['foo:export:collection']
          paginationEnabled: false
          filters: ['foo.search_filter']
          # output: App\Dto\FooDto
          # processor: App\State\FooExportProcessor
          # provider: App\State\FooExportProvider